[project]
name = "tic-tac-toe"
version = "0.1.0"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.23.0",
    "pydantic>=2.0.0",
    "sqlalchemy>=2.0.0",
    "requests>=2.31.0",
    "pytest>=7.0.0",
]

